CREATE TABLE medicamentos (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    laboratorio VARCHAR2(100) NOT NULL,
    fecha_fabricacion DATE NOT NULL,
    fecha_vencimiento DATE NOT NULL,
    cantidad_stock NUMBER NOT NULL,
    valor_unitario NUMBER(10,2) NOT NULL
);
SELECT * FROM medicamentos;

SELECT * FROM ventas;

DROP TABLE medicamentos CASCADE CONSTRAINTS;
DROP TABLE medicamento CASCADE CONSTRAINTS;

CREATE TABLE ventas (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_hora TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    medicamento_id NUMBER NOT NULL,
    cantidad NUMBER NOT NULL,
    valor_unitario NUMBER(10,2) NOT NULL,
    valor_total NUMBER(10,2) NOT NULL,
    CONSTRAINT fk_medicamento FOREIGN KEY (medicamento_id) REFERENCES medicamentos(id)
);
